parser: babel-eslint
plugins:
  - react

# So parent files don't get applied
root: true

env:
  es6: true
  node: true
  mocha: true

rules:
  brace-style: [2, 1tbs, {allowSingleLine: false}]
  comma-spacing: [2, {before: false, after: true}]
  comma-style: [2, last]
  computed-property-spacing: [2, never]
  eqeqeq: [2, smart]
  eol-last: 2
  indent: [2, 2, {SwitchCase: 1}]
  jsx-quotes: [2, prefer-double]
  key-spacing: 2
  keyword-spacing: 2
  max-len: 0 # TODO
  no-unused-expressions: 2
  no-unused-vars: 2
  no-shadow: 2
  no-spaced-func: 2
  no-multi-spaces: 2
  no-undef: 2
  no-dupe-keys: 2
  no-dupe-args: 2
  no-duplicate-case: 2
  no-cond-assign: 2
  no-extra-semi: 2
  no-extra-boolean-cast: 2
  no-trailing-spaces: 2
  no-unreachable: 2
  no-var: 2
  object-curly-spacing: [2, always]
  prefer-arrow-callback: 2
  prefer-const: 2
  quotes: [2, single, avoid-escape]
  semi-spacing: 2
  semi: [2, always]
  space-infix-ops: 2
  space-unary-ops: [2, { words: true, nonwords: false }]
  react/jsx-uses-react: 2
  react/jsx-uses-vars: 2
